### ISSUE TITLE
Design Site Iconography

### ISSUE THREAD

**Issue by jpbream** [Tech-Nc-State/tech-at-hub#13]
We need a favicon, as well as a general site logo. If someone who knows some graphic design wants to pick this up, that would be great.

When finished, you can convert the logo to a .ico file. It will need to be the proper dimensions for a favicon. Replace the current ```frontend/src/favicon.ico``` file with the new logo, and the site will automatically display it on the browser tab.

**Comment by cgreene682** [comment]
Logo and favicon has been added to the site, so this issue is resolved
