### ISSUE TITLE
Create Account Page

### ISSUE THREAD

**Issue by jpbream** [Tech-Nc-State/tech-at-hub#23]
- Should be linked from the login page
- Username (must be unique, tell user if its not unique)
- Password (basic password checking)
- Re-enter password
- Email
- DOB

**Comment by Heckin-Doggo** [comment]
Should security questions (for potential password reset) be a part of the create account page? Or should it be on a separate page?

**Comment by jpbream** [comment]
@hrishibatta Can you push the branch you are working on for this to the Github? I can make a pull-request for it so we can see the changes
