### ISSUE TITLE
Uploading/Storing user profile pictures

### ISSUE THREAD

**Issue by Heckin-Doggo** [Tech-Nc-State/tech-at-hub#27]
I don't think we can store profile pictures in a database, so we'd need to store a reference to an image stored somewhere else.
Additionally, for file uploads, we should probably compress incoming images or just have a way to limit file size before uploading. Maybe both.

**Comment by jpbream** [comment]
We need an endpoint in the `UserController` class called `UploadProfilePicture`. It can be routed to something like `/upload`, just pick something that makes sense.

This endpoint will be a POST request and accept a `File` as an input. You will need to research how to do this, we don't have any examples of it yet. This endpoint should also require the user to be authenticated.

In addition, we need to create a folder somewhere to house these profile pictures. You can create it in the root directory of the `tech_at_hub` project and add it to the `.gitignore`.

Upon receiving the uploaded file, save it into this folder you created earlier. You can look into the idea @Heckin-Doggo suggested of compressing it, C# can make complicated things like that very simple sometimes. Another thought I had was hashing the image and naming the file the hash. That way, if two users have the same profile picture we only need to store the image once.

Once you save the file, update the current user's `ProfilePicturePath` to point to that file, and save them back to the database.

**Comment by jpbream** [comment]
@Buddwaur Here is a more fleshed out issue for what we discussed tonight
