### ISSUE TITLE
Git Service Wishlist

### ISSUE THREAD

**Issue by jpbream** [Tech-Nc-State/tech-at-hub#42]
Here are the things our `GitService` will need to be able to do. Each one of these bullets will be a large task. We might do one person per bullet point.

- `GetBranches()` - Return a list of branches in the repository. Each entry should include the branch name and the SHA of the HEAD commit
- `GetTags()` - Return a list of tags in the repository. Same deal as with the branches
- `GetDirectoryListing(dir, branch/commit)` - Return the contents of a particular directory on a particular branch or commit. This would return a list of `DirectoryEntry` objects
- `GetFileContents(file, branch/commit)` - Return the contents of a particular file on a particular branch or commit. This would return  a list of `FileContent` objects
- `GetCommitLog(branch)` - Gets the commit log of a particular branch in the repository. This would return a list of `Commit` objects.

** Note: The following are NOT database objects. They are C# classes we will create to be sent back to the frontend, but they are not stored in the database. They represent information within the git filesystem.

### Commit Object
 - Timestamp
 - User (who made the commit + their profile picture)
 - Commit message
 - SHA
 - Diff (how to implement this?)

### DirectoryEntry Object
- File/Folder name
- Last Commit (reference to a Commit object, this will depend on the branch that was asked for)
- Last Update (could come from the Commit reference)

### FileContent Object
- Name
- Size
- Contents
- Last Commit (reference to a Commit object, will depend on branch that was asked for)

**Comment by Heckin-Doggo** [comment]
Completed: 
`GetDirectoryListing()`
`GetTags()`
`GetBranches()`
`GetFileContents()`

I think only `GetCommitLog()` is leftover.

**Comment by Heckin-Doggo** [comment]
Notes on GetCommitLog():
`git cat-file -p <hash>` does different fun stuff depending on the type of the file.
`git cat-file -t <hash>` will tell you the type of the file, including `commit`, `blob`, `tree`
You can do this on the branch names too (in place of <hash>), which should be of type `commit` which point to a hash of the last commit for that branch.

Doing `git cat-file -p <hash>` on the following types seem to produce the following outputs:
* `commit` > produces output that looks like:
```
tree c33dfdaa4235fe07f54c8ca0c5f94d363af1fcf9
parent 1f756b87f9f4d13b1a2b05818dadcdfdb69a4e16
author Neil Bennett <nzbennet@ncsu.edu> 1668560510 -0500
committer Neil Bennett <nzbennet@ncsu.edu> 1668560510 -0500

aiweh
```
Consists of the structure:
* tree hash
* parent(commit?) hash
* author name <email> timestamp -timezone
* committer name <email> timestamp -timezone
* empty line
* commit message

* `blob` > just the contents of the file. gotta use tree or commt log to find what it actually means.
* `tree` > has a list of files affected by this commit + their last associated commit log. appears to use a commit hash, needs further investigation.


TODO: Update this and make sure its accurate.

Using: https://git-scm.com/book/en/v2/Git-Internals-Git-Objects

**Comment by Heckin-Doggo** [comment]
Some information on the git folder structure: 
```
/.git
|- COMMIT_EDITMSG  // last commit's message
|- FETCH_HEAD  // unknown
|- HEAD  // ref: <path_to_head>
|- ORIG_HEAD  // contains hash (of base head?)
|- config  // very simple file of true/false values for some tags. these show when running `git config --list`
|- description  // message saying repo is unnamed. obsolete?
|- index  // special index file of all files in the repo. see https://git-scm.com/docs/index-format
|- /logs  // empty?
|- /info
   |- exclude  // commented out file, unknown use
|- /objects  // contains files identified by hash: these are read by cat-file. contains vary by type.
|- /refs
   |- /heads  // contains all branch files (named), which contain commit hash
   |- /tags  // contains all tag files (named), which contain commit hash
```

**Comment by Heckin-Doggo** [comment]
It looks like we'll be able to take the tree object for a branch to get a commit log.
![image](https://user-images.githubusercontent.com/43428231/217126575-3f8a8736-0683-4950-b61e-5ae607248c0c.png)

This test was made using 4 commits each having one `itemX.txt` per commit. I will try next making multiple objects per branch, as well as editing a file.
