### ISSUE TITLE
Fix the API Design

### ISSUE THREAD

**Issue by jpbream** [Tech-Nc-State/tech-at-hub#77]
Fix up the current API design to match the page created in the docs

**Comment by Heckin-Doggo** [comment]
Current problems noted (endpoint level):
`POST /user/change` should be `PUT /user/change`

TODO: Take a look internally and make sure the inputs and outputs align with expected in Wiki.

**Comment by Heckin-Doggo** [comment]
Internal check: 
User:
* GET /user/get/{id} - OK
* GET /user/me - OK except `profilePicturePath` returns null. probably not set though.
* POST /user - OK except for the issue in #83.
* PUT /user/change - change HTTP call to "PUT". I think it works tho.
Auth:
* POST /auth/login - OK
* GET /auth/gitclient - ?

TODO: It has occured to me that this might be talking about the swagger UI documentation. Whoops.
